<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tpl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{%?</string>
	<key>foldingStopMarker</key>
	<string>%?\}</string>
	<key>name</key>
	<string>Fenom</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.fenom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(%?\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.fenom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>source.fenom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#lang</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{%?)\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.fenom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*(%?\})</string>
					<key>name</key>
					<string>comment.block.fenom</string>
					<key>patterns</key>
					<array/>
				</dict>
			</array>
		</dict>
		<key>lang</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\|=|\+=|-=|\*=|\%=|!==|=|&=|\^=|~|/=|\-|\+|/ |\*|!=|!|&lt;=|&gt;=|&lt;|&gt;|===|==|%|&amp;&amp;|\|\|)|\b(and|or|xor)\b</string>
					<key>name</key>
					<string>keyword.operator.fenom</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(TRUE|FALSE|true|false)\b</string>
					<key>name</key>
					<string>constant.language.fenom</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|set|if|else|elseif|foreach|foreachelse|autoescape|autotrim|for|extends|block|use|parent|filter|break|continue|forelse|ignore|include|insert|macro|import|raw|switch|case|unset)\b</string>
					<key>name</key>
					<string>keyword.control.fenom</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.fenom</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([a-zA-Z]+)=</string>
					<key>name</key>
					<string>meta.attribute.fenom</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(plus|from|as|capture|default|cycle)\b</string>
					<key>name</key>
					<string>support.function.built-in.fenom</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(match|ematch|date_format|upper|up|ereplace|escape|esplit|join|length|replace|strip_tags|strip|truncate|split|count|declination|catinfo|dateformat|limit|image)|(%|)(in)\b</string>
					<key>name</key>
					<string>support.function.variable-modifier.fenom</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fenom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fenom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.fenom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.fenom</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.fenom</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.fenom</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.fenom</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.fenom</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fenom</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(\$)Fenom\.</string>
					<key>name</key>
					<string>variable.other.global.fenom</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fenom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.fenom</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)([a-zA-Z_][a-zA-Z0-9_]*)\b|(\$.)([a-zA-Z_.][a-zA-Z0-9_.]*)\b</string>
					<key>name</key>
					<string>variable.other.fenom</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.fenom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.fenom</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
					<key>name</key>
					<string>variable.other.fenom</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.fenom</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.object.fenom</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fenom</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fenom</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)([a-zA-Z_][a-zA-Z0-9_]*)(\().*?(\))</string>
					<key>name</key>
					<string>variable.other.fenom</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.fenom</string>
	<key>uuid</key>
	<string>316a7c87-7ec7-4b41-b366-7d8832228af0</string>
</dict>
</plist>
